application: blog
version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.db

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /static/css
  static_dir: static/css
  expiration: "7d"

- url: /static/js
  static_dir: static/js
  expiration: "7d"

- url: /static/img
  static_dir: static/img
  expiration: "7d"
  
- url: .*
  script: blog.app
  
libraries:
- name: jinja2
  version: latest